name: League Rank Tracker

on:
  schedule:
    - cron: "0 * * * *" # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.32.0
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests

      - name: Set up Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run script
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          SUMMONER_ID: ${{ secrets.SUMMONER_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          PUUID: ${{ secrets.PUUID }}
        run: python main.py

      - name: Commit changes
        if: success()
        run: |
          git add last_data.json
          git commit -m "Update last_data.json [skip ci]" || echo "No changes to commit"
          git push
